runtime: aspnetcore
env: flex

env_variables:
	DB_USER: <your-username>
    DB_PASS: <password>
    DB_NAME: <dbname>
    INSTANCE_HOST: cloudsql
    
beta_settings:
    cloud_sql_instance: "<project-name>:<region>:<instance-name>=tcp:3306"